- name: Install Nginx rpm
  sudo: true
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm state=present

- name: Install Nginx
  sudo: true
  yum: name=nginx
  
- name: Template nginx
  sudo: true
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: Restart nginx
  
- name: Enable Nginx
  sudo: yes
  service: name=nginx state=running enabled=yes
