- name: Install MySQL5.6
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm
    - MySQL-python
    - mysql
    - mysql-devel
    - mysql-server
    - mysql-utilities
  
- name: Enable MySQL
  sudo: yes
  service: name=mysqld state=running enabled=yes

- name: Set MySQL root password
  sudo: yes
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"

- name: Template ~/.my.cnf
  sudo: yes
  template:
    src: my.cnf
    dest: "/root/.my.cnf"
    mode: 0600
  notify: Restart mysql
